version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ciro-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: unless-stopped

networks:
  default:
    name: ciro-network
    external: true 