version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ciro-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: unless-stopped
    # Disable health check temporarily
    healthcheck:
      disable: true
    
    # Original health check (commented out)
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "6333"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s 